A small café tracks its daily sales for three products: coffee, sandwiches, and cakes. The sales for three days are recorded as:
Day 1: [100 coffees, 50 sandwiches, 30 cakes]
Day 2: [120 coffees, 70 sandwiches, 40 cakes]
Day 3: [90 coffees, 60 sandwiches, 20 cakes]
The prices for the products are:
Coffee: $2 each
Sandwich: $5 each
Cake: $4 each
Represent the sales and prices as matrices.
Compute the total revenue for each day using matrix multiplication.
Calculate the transpose of the sales matrix and explain its significance.

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

here, in the sales matrix, each row represents a product and each column represents a day

In [5]:
sales = np.array([[100, 120, 90],
                  [50, 70, 60],
                  [30, 40, 20]])

prices = np.array([[2,5,4]])

In [7]:
revenue = np.dot(prices, sales)
print(revenue)

[[570 750 560]]


In [8]:
transpose = sales.T
print(transpose)

[[100  50  30]
 [120  70  40]
 [ 90  60  20]]


After transposing the sales matrix, the orientation is inersed, thus now column represents a product and each row represents a day.

The signinficance of transpose of matrix are as follow:
1. Transpose of matrix is used to convert non squared matrix to be in desired orientation making it suitable for matrix multiplication.
2. PCA involves eigenvector decomposition of the covariance matrix. Transpose is used to compute the covariance matrix and project data onto the principal components.
3. The transpose is used in transformations such as rotations, projections, and changing coordinate systems in computer vision and natural language processing.